language: elixir

elixir:
  - 1.5.0

otp_release:
  - 20.0

matrix:
  include:
    - elixir 1.5.0
      otp_release 20.0
    - elixir: 1.5.2
      otp_release: 20.1

script:
  - mix credo --strict
  - mix test
